// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission6_jacklin5.Models;

namespace mission6_jacklin5.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20230220233501_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("mission6_jacklin5.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Animated"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Children's"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Romance"
                        });
                });

            modelBuilder.Entity("mission6_jacklin5.Models.MovieForm", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 7,
                            Director = "Rob Reiner",
                            Edited = false,
                            Lent = " ",
                            Notes = "This is a great film!",
                            Rating = "PG",
                            Title = "The Princess Bride",
                            Year = (ushort)1987
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 6,
                            Director = "Tom McGrath",
                            Edited = false,
                            Lent = "Brady Jacklin",
                            Notes = "Too many baby bums",
                            Rating = "PG",
                            Title = "Boss Baby",
                            Year = (ushort)2017
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 2,
                            Director = "Rob Minkoff",
                            Edited = false,
                            Lent = "Kimball Shupe",
                            Notes = "The greatest film in history",
                            Rating = "PG",
                            Title = "Mr. Peabody and Sherman",
                            Year = (ushort)2014
                        });
                });

            modelBuilder.Entity("mission6_jacklin5.Models.MovieForm", b =>
                {
                    b.HasOne("mission6_jacklin5.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
