// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission6_jacklin5.Models;

namespace mission6_jacklin5.Migrations
{
    [DbContext(typeof(MoviesContext))]
    partial class MoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("mission6_jacklin5.Models.MovieForm", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Romance",
                            Director = "Rob Reiner",
                            Edited = false,
                            Lent = " ",
                            Notes = "This is a great film!",
                            Rating = "PG",
                            Title = "The Princess Bride",
                            Year = (ushort)1987
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Animated, Comedy",
                            Director = "Tom McGrath",
                            Edited = false,
                            Lent = "Brady Jacklin",
                            Notes = "Too many baby bums",
                            Rating = "PG",
                            Title = "Boss Baby",
                            Year = (ushort)2017
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Animated, Comedy",
                            Director = "Rob Minkoff",
                            Edited = false,
                            Lent = "Kimball Shupe",
                            Notes = "The greatest film in history",
                            Rating = "PG",
                            Title = "Mr. Peabody and Sherman",
                            Year = (ushort)2014
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
